# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "colorize", "~> 0.8.1"

gem "csv", "~> 3.2"

gem "terminal-table", "~> 3.0"

gem "artii", "~> 2.1"

gem "rspec", "~> 3.10"
